name: My First GitHub Actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
     
    - name: Install docker
      uses: docker/build-push-action@v2
      with:
        docker-version: '20.10.7'  # Specify the desired Docker version

    - name: Build Docker Image
      run: docker buildx build -t ghcr.io/janakiprasadaws/GitHub-Actions-Workflows/github-image:latest .
      working-directory: working-directory/Dockerfile

    - name: Authenticate with GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" 
      
    - name: Push Docker Image to GitHub Container Registry
      run: docker push ghcr.io/Janakiprasadaw/GitHub-Actions-Workflows/github-image:latest

    
